name: Docker Image CI
on:
  workflow_dispatch:
    inputs:
      test_list:
        description: Only run tests that match the regular expression
        default: ""
        required: false
      img:
        description: Kraken image location
        default: quay.io/openshift-scale/kraken:testing
        required: false
  push:
    branch: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login in quay
      run: docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USER_1 }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN_1 }}
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build the Docker images
      run: docker-compose build --parallel
    - name: Push the Docker images
      run: docker-compose push