name: Docker Image CI
on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login in quay
      run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
    - name: Check out code
      uses: actions/checkout@main
    - name: Build the Docker images
      run: docker-compose build
    - name: Push the Docker images
      run: docker-compose push