name: Run e2e tests
on:
  pull_request:
    types: ['synchronize', 'edited', 'opened', 'reopened']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '*/README.md'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Test User'
jobs:
  e2e:
    name: E2E testing
    runs-on: ubuntu-latest
    timeout-minutes: 600
    if: "github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request')"
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Login in quay
      run: podman login quay.io --username="${QUAY_USER_1}" --password="${QUAY_TOKEN_1}"
      env:
        QUAY_USER_1: ${{ secrets.QUAY_USER_1 }}
        QUAY_TOKEN_1: ${{ secrets.QUAY_TOKEN_1 }}
    - name: Authenticate against OCP cluster
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_username: ${{ secrets.OPENSHIFT_USER }}
        openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
        insecure_skip_tls_verify: true

    - name: ls
      run: ls
    - name: Execute e2e tests
      run: ./CI/run.sh
      env:
        TERM: linux
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        VPC_ID: ${{ secrets.VPC_ID }}
        SUBNET_ID: ${{ secrets.SUBNET_ID }}

    - name: Remove all podman images
      run: docker rm -vf --all; docker rmi -f --all
      if: always() # always run even if the previous step fails
